### ISSUE TITLE
Activity values has never been updated since first launch

### ISSUE THREAD

**Issue by yoosee** [Fitbit/sdk-moment#4]
It seems that Activity values (like steps) has never been updated. 

I put some debug output by console.log and it seems that tickHandler in acrivity.js has been called in every "tick" but get*() functions from activityData has only called at the first time and never been called again. from index.js, only the same value returned any time following line called.

    txt.text = data[Object.keys(data)[index]].pretty;

I compared value in index.js like: 

    console.log("Steps: " + data[Object.keys(data)[index]].pretty + " vs " + today.adjusted.steps);

and it shows different value (today.adjusted.steps updated while previous one never).

**Comment by yoosee** [comment]
It might be like that? It worked in my environment.

```
function tickHandler(evt) {
  activityData = updateActivities();
  activityCallback(activityData);
}

let updateActivities = () => {
  return {  
    steps: getSteps(),
    calories: getCalories(),
    distance: getDistance(),
    elevationGain: getElevationGain(),
    activeMinutes: getActiveMinutes()
  };  
}
```

**Comment by NicholasConrad** [comment]
Currently activityData is defined only when activity.js is initialized. Put in inside tickHandler and it will update as expected:
```
function tickHandler(evt) {
  let activityData = {
  steps: getSteps(),
  calories: getCalories(),
  distance: getDistance(),
  elevationGain: getElevationGain(),
  activeMinutes: getActiveMinutes()
  }
  activityCallback(activityData);
}

**Comment by yoosee** [comment]
I built and run the latest sdk-moment code in FitBit OS Simulator and it does't update activity values on its clock face (steps stayed specific number for more than 5 min, while my other app updates the value in Simulator). I could agree the code should update the value in every tick but might be cached? or my environmental issue?

![sdk-moment-test-screenshot](https://user-images.githubusercontent.com/92736/41526657-d84c69a4-731f-11e8-908c-9c5b83939e37.png)
![sdk-moment-test-screenshot 2](https://user-images.githubusercontent.com/92736/41526656-d814d6a6-731f-11e8-9d59-b428f3dd8090.png)

**Comment by NicholasConrad** [comment]
@Yoosee, It's not local to you, the issue effected me as well. Look at code example in my last comment, that will update your activityData on each tick.

**Comment by yoosee** [comment]
OK, understood. Thanks!
